version: '3.1'

services:
  db:
    image: mysql
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: 
      MYSQL_USER: 
      MYSQL_PASSWORD: 
    ports:
      - '${MYSQL_PORT}:3306'
    volumes:
      - PayomLibrary:/var/lib/mysql
    command: [
              'mysqld', '--character-set-server=utf8mb4', 
              '--collation-server=utf8mb4_unicode_ci',
              '--default-time-zone=Asia/Bangkok'
            ]

volumes:
  PayomLibrary: